name: wazo-plugin-demo
namespace: quintana
version: 0.0.1
author: Sylvain Boily
display_name: Plugin Demo
plugin_format_version: 1
min_wazo_version: 21.07
tags:
  - community
  - demo
#depends:
#  - name: foo
#    namespace: foocorp
debian_depends:
  - vim
homepage: https://github.com/sboily/wazo-plugin-demo
